### ISSUE TITLE
Remote Playlist Play failing

### ISSUE THREAD

**Issue by Sparky939** [owlbear-rodeo/kenku-fm#24]
**Describe the bug**
When set up the some of the remote endpoints aren't responding to requests (playlist/play for instance)

**To Reproduce**
Run the following .bat script:
.bat script:
`curl --request PUT --url 127.0.0.1:3333/v1/playlist/play --header 'Content-Type: application/json' --data '{ "id": "4f6f8642-c442-46a3-aed7-af38796faf21" }'`

**Expected behavior**
The playlist should start playing

**Screenshots**
None

**Desktop (please complete the following information):**
OS: Windows

**Additional context**
response:
`{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: application/x-www-form-urlencoded"}curl: (6) Could not resolve host: application
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: 4f6f8642-c442-46a3-aed7-af38796faf21
curl: (3) unmatched close brace/bracket in URL position 1:
}'`

**Comment by nthouliss** [comment]
Could you please fill out a bug report? It would make it easier for us to try and reproduce and narrow-down what could be happening

**Comment by Sparky939** [comment]
It's a .bat script aimed at the remote with the remote server defaults
Then again, I'm also debugging it second hand for a friend, so the information I can provide is very limited.

**Comment by nthouliss** [comment]
Cheers, appreciate the formatting. It may seem little but it helps to find the information quickly. 

I can confirm that this is just a syntax issue. The documentation formats the curl request for use on a Unix-like system (Mac). Your friend needs to edit the curl request to accept the windows style. 

`curl --request PUT --url 127.0.0.1:3333/v1/playlist/play --header "Content-Type: application/json" --data "{ \"id\":\"4f6f8642-c442-46a3-aed7-af38796faf21\"}"`

In future, if they run into a curl issue they should use `-v` to get a verbose output, which will help track down the issue. 

I'll create an issue to update the documentation so that other people are aware of the syntax difference.
