### ISSUE TITLE
Nothing happens when selecting or dropping multiple files

### ISSUE THREAD

**Issue by m4rcLs** [owlbear-rodeo/kenku-fm#28]
**Describe the bug**
While adding a track nothing happens when selecting or dropping multiple files.

**To Reproduce**
1. Go to any Playlist or Soundboard
2. Add Track
3. Select or drop multiple files

**Expected behavior**

Looking at the code it should take first of the files but this does not happen for me.  
Weirdly I also get no warning messages for the file input when I'm inputting wrong file formats.  

**Screenshots**
![04GT7tEz5B](https://user-images.githubusercontent.com/31926457/161414184-b2ae3ad4-dc80-4010-86d8-e2b3fb6232dc.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.0

**Comment by mitchemmc** [comment]
The add track screen only supports a single file.
For multiple files at a time please see our drag and drop support here https://www.kenku.fm/docs/using-kenku-player

We should probably limit the file selection dialog to a single file, currently this is a bug with us using `maxFiles: 1` instead of `multiple: false` as our file input parameters.

I'll schedule this for a fix but it may be a bit as it is a minor bug.

**Comment by mitchemmc** [comment]
Please see the documentation I linked above.
Drag and drop will grab the file name if you drop it into the playlist screen, not if you drop into the add track dialog.
See the first video in the "Adding Audio Files to a Playlist or Soundboard" section in the documentation for an example of this.

**Comment by m4rcLs** [comment]
Oh damn, I totally missed that! This is very much what I wanted. Thanks a lot :)
