### ISSUE TITLE
[BUG] When playing any audio through the Kenku Browser, audio becomes distorted/stutters after some time. 

### ISSUE THREAD

**Issue by AkimboGogurts** [owlbear-rodeo/kenku-fm#37]
**Describe the bug**
When playing audio through the browser after a fresh start of the app, audio will become slowed and distorted after 10-20 seconds of normal playback. The sound is quite strange, it sounds like its going into slo-mo (literally pitch shifting down) and when it finishes that it will begin to cut in and out every 1-2 seconds. 

This issue was posted about on reddit here: https://www.reddit.com/r/OwlbearRodeo/comments/ugmzaj/kenku_fm_audio_starting_slowed_down_and_then_cuts/

Changing performance mode has no impact on the behavior, and it is consistent between outputting to the local computer and a discord bot connection. CPU usage during these periods does not spike, plenty is available for use. 

I've cleared my Appdata Kenku folder in an attempt to reconfigure the issue/start fresh and even playing from a fresh state the issue continues. 

**To Reproduce**
1. Launch Kenku FM
2. Open a Browser Tab (Spotify, Youtube, anything)
3. Play a track and wait.
4. Issue occurs when outputting to the local computer or a discord bot. 

**Expected behavior**
Audio should play normally. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 21H2  (22000.613)

**Additional context**
N/A

**Comment by AkimboGogurts** [comment]
After some more poking and prodding I was able to get this to resolve by restarting my computer a couple times. I have a Windows 11 laptop that I threw it on for testing as well and experienced the same issue. After some reboots on the second PC the behavior described here has resolved, however audio playback on the Laptop is still choppy. 

It could be a good idea to suggest a reboot after setup to potentially get around this.

**Comment by AkimboGogurts** [comment]
Hey I just want to quickly bump this issue, I'm running into this problem again about 2 months after the initial problem was resolved by a reboot. 

I've reinstalled, rebooted multiple times and the issue continues to persist, any ideas or workarounds for this? 

Thanks.

**Comment by GlitchTech** [comment]
I'm experiencing similar. Windows11 machine though my distortion and stuttering is from the get go. Kenku is the only thing running. Tested the same audio files on a Windows 10 machine and a Mac but didn't have the audio issues.

OS Name		Microsoft Windows 11 Home
Version		10.0.22000 Build 22000
Processor	11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz, 3302 Mhz, 4 Core(s), 8 Logical Processor(s)
RAM		16.0 GB

**Comment by PragmaticBeaver** [comment]
Bumping this one

**Comment by YenBenGrey** [comment]
I am also getting jittery play just through discord bot. Was working perfectly until about two weeks ago.

I am on MacOS Ventura 13.0.

**Comment by YenBenGrey** [comment]
Just an update, mine is working perfectly well today. Bizarre :-)

**Comment by YenBenGrey** [comment]
Another update, tonight (22:00 GMT) back to being jittery :-(

**Comment by mitchemmc** [comment]
I've had some time in between our VTT releases to look into this.
In v1.2.0 we've made some adjustments to hopefully help reduce this issue.
I don't think it's ever going to be completely solved because it's related to how much CPU you're using but it should now be a lot less likely to happen.

I'm going to close this for now but if it keeps happening comment here and I'll look further into it.

**Comment by LiamVA** [comment]
@mitchemmc I have a Ryzen 9 5950x cpu, 64g of ram and I am utilizing 50%  cpu with 45% ram and I'm having this issue. I also have an issue when using multiple sounds on a sound board that it tends to just stop playing and says "unable to play sound". Only fix I've found thus far is to completely stop everything running on kenku and reboot. Which, reboots quickly, just kinda of a damper on a DnD campaign.

**Comment by djashdj** [comment]
I have had this issue since day one.  I reboot before each session but it still occurs.  I use Syrinscape for audio, open it in the kenku browser, and locally or on discord it does the weird pitch bendy stuff, cracks and pops in audio, OFTEN when other browsers kick in "dndbeyond" or anything really.  Often seems like anything to do with network traffic.  

Windows 11 PC  
AMD 5900 12 cpu
64GB ram
Killer NIC 1GB  

I'm wired and not on wifi as well.  

If you need help troubleshooting, logs or something let me know and I'll get them I'm fairly tech savvy.

**Comment by djashdj** [comment]
Yep clicked, "comment" and pitch bend ensued.
